export const COMENZAR_DESCARGA_USUARIOS = "COMENZAR_DESCARGA_USUARIOS";
export const DESCARGA_USUARIOS_EXITOSA = "DESCARGA_USUARIOS_EXITOSA";
export const DESCARGA_USUARIOS_ERROR = "DESCARGA_USUARIOS_ERROR";
export const OBTENER_USUARIO_ELIMINAR = "OBTENER_USUARIO_ELIMINAR";
export const USUARIO_ELIMINADO_EXITO = "USUARIO_ELIMINADO_EXITO";
export const USUARIO_ELIMINADO_ERROR = "USUARIO_ELIMINADO_ERROR";
export const AGREGAR_USUARIO = "AGREGAR_USUARIO";
export const AGREGAR_USUARIO_EXITO = "AGREGAR_USUARIO_EXITO";
export const AGREGAR_USUARIO_ERROR = "AGREGAR_USUARIO_ERROR";
export const OBTENER_USUARIO_EDITAR = "OBTENER_USUARIO_EDITAR";
export const COMENZAR_EDICION_USUARIO = "COMENZAR_EDICION_USUARIO";
export const USUARIO_EDITADO_ERROR = "USUARIO_EDITADO_ERROR";
export const USUARIO_EDITADO_EXITO = "USUARIO_EDITADO_EXITO";

export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION_EXITO = "CERRAR_SESION_EXITO";
export const REDIRECT_LOGIN_FALSE = "REDIRECT_LOGIN_FALSE";

export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const ELIMINAR_USUARIO = "ELIMINAR_USUARIO";
export const USUARIO_ACTUAL = "USUARIO_ACTUAL";
